# Creator: Kurt M. Weber
# Created on: 2025-01-05

# This file is part of quanta, a component of the Cosmoverse.
# Licensed under Hippocratic License with clauses:
# HL3-CL-ECO-EXTR-FFD-MEDIA-MY-SUP-SV-TAL-USTA-XUAR
# See file LICENSE for full licensing information.

all: hashtable.c
	gcc -c hashtable.c -o hashtable.o -I../$(FILAMENT_INCLUDE) -I../$(QUANTA_INCLUDE) -D ENV_HOSTED